### ISSUE TITLE
Wrong grid cell calculation with a value of 100 in column chart

### ISSUE THREAD

**Issue by GoOz** [ffoodd/chaarts#55]
It's easily reproducible with your online example.

On the multiple columns chart, when a column has a value of 100, it's placement turns wrong and shift the other columns' placement after it.

See the video below.

https://user-images.githubusercontent.com/1280069/107647868-e8f3c880-6c7b-11eb-9e63-36a6819e0a00.mp4

I guess something is wrong in this declaration…

```css
.chaarts[class*="column"] td {
  grid-row: calc( 100 - var(--value) )/-3;
}
```
… but I'm not sure what the `-3` is for, although I can confirm that without it the 99 other values won't work 😅
